# Site settings
title: Pagar.me Developers
description: Um blog feito pelos desenvolvedores do Pagar.me
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://developers.pagar.me" # the base hostname & protocol for your site
disqusid_shortname: pagarme

markdown: kramdown
paginate: 100
permalink: /blog/:categories/:title
paginate_path: /blog/pagina/:num/

# Exclude development-only stuff
exclude: ['.bowerrc', '.gitignore', '_config.yml', 'bower.json', 'feed.xml', 'gulpfile.js', 'package.json', 'LICENSE', 'README.md', 'source', 'node_modules', 'vendor']

